### ISSUE TITLE
stats layout

### ISSUE THREAD

**Issue by fluviangumbo** [fluviangumbo/Management-Calendar#9]

**Comment by bungin** [comment]
OUTDATED, NO GOOD
stats should/will include: 
employee/employees assigned to day,
assigned/unassigned jobs,
hours assigned,
assigned employee(s) present,

![Image](https://github.com/user-attachments/assets/41a56106-cafb-4fce-a5b6-aa2148fe4f73)

**Comment by bungin** [comment]
how to present stats about tasks and employee details.
![layout2](https://github.com/user-attachments/assets/cd1a4665-ea4d-49dc-8c2d-a1f6e026ca5b)

**Comment by bungin** [comment]
need to decide on functionality of the fields and button(s). if we want the fields to be dropdowns, the pictures function will be hover. if we want expanded info on click we will need a second button, the first existing button being "new", the second being "edit".

**Comment by bungin** [comment]
for now the stats are: emp names, tasks, and who is assigned to what. 
for now dont worry too much about the page being unpopulated.
